import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync, unlinkSync } from 'node:fs'
import { homedir } from 'node:os'
import { resolve, basename } from 'node:path'

const CLAUDITOR_DIR = resolve(homedir(), '.clauditor')
const SESSIONS_DIR = resolve(CLAUDITOR_DIR, 'sessions')
// Keep legacy path for backward compat reads
const LEGACY_SESSION_FILE = resolve(CLAUDITOR_DIR, 'last-session.md')

const MAX_HANDOFF_AGE_MS = 24 * 60 * 60 * 1000 // 24 hours

export interface SessionStateData {
  savedAt: string
  branch: string | null
  turns: number
  tokensPerTurn: number
  wasteFactor: number
  filesModified: string[]
  cwd: string | null
  /** The user's original task/prompt */
  originalTask: string | null
  /** Last 3 user messages (often contain key decisions) */
  recentUserMessages: string[]
  /** Git commits made during the session */
  gitCommits: string[]
  /** Key bash commands and outcomes (tests, builds, deploys) */
  keyCommands: string[]
  /** Files read during the session */
  filesRead: string[]
  /** Last assistant message (often contains next steps / plan) */
  lastAssistantMessage: string | null
}

/**
 * Encode a cwd path into a safe directory name.
 */
function encodeCwd(cwd: string): string {
  return cwd.replace(/[^a-zA-Z0-9]/g, '-').replace(/-+/g, '-').slice(0, 100)
}

/**
 * Get the sessions directory for a given cwd.
 */
function getSessionsDir(cwd: string | null): string {
  if (!cwd) return SESSIONS_DIR
  return resolve(SESSIONS_DIR, encodeCwd(cwd))
}

/**
 * Save session state to ~/.clauditor/sessions/<encoded-cwd>/<timestamp>.md
 * Each save creates a new file. SessionStart reads recent files and presents choice if multiple.
 */
export function saveSessionState(data: SessionStateData): void {
  try {
    const dir = getSessionsDir(data.cwd)
    mkdirSync(dir, { recursive: true })

    const filesList = data.filesModified.length > 0
      ? data.filesModified.slice(0, 15).join(', ')
      : 'none tracked'

    const sections: string[] = [
      `# Last Session (saved by clauditor)`,
      ``,
      `- **Saved at:** ${data.savedAt}`,
      `- **Branch:** ${data.branch || 'unknown'}`,
      `- **Project:** ${data.cwd || 'unknown'}`,
      `- **Session size:** ${data.turns} turns, ${data.tokensPerTurn}k tokens/turn`,
      `- **Waste factor:** ${data.wasteFactor}x`,
      `- **Files modified:** ${filesList}`,
    ]

    if (data.filesRead && data.filesRead.length > 0) {
      sections.push(`- **Files read:** ${data.filesRead.slice(0, 15).join(', ')}`)
    }

    if (data.originalTask) {
      sections.push(``, `## Original Task`, data.originalTask)
    }

    if (data.gitCommits && data.gitCommits.length > 0) {
      sections.push(``, `## Commits Made`)
      for (const commit of data.gitCommits.slice(0, 10)) {
        sections.push(`- ${commit}`)
      }
    }

    if (data.keyCommands && data.keyCommands.length > 0) {
      sections.push(``, `## Key Commands & Results`)
      for (const cmd of data.keyCommands.slice(0, 10)) {
        sections.push(`- ${cmd}`)
      }
    }

    if (data.recentUserMessages && data.recentUserMessages.length > 0) {
      sections.push(``, `## Recent User Messages`)
      for (const msg of data.recentUserMessages) {
        sections.push(`> ${msg}`)
      }
    }

    if (data.lastAssistantMessage) {
      sections.push(``, `## Where We Left Off`, data.lastAssistantMessage)
    }

    sections.push(``)

    const timestamp = Date.now()
    const filePath = resolve(dir, `${timestamp}.md`)
    writeFileSync(filePath, sections.join('\n'))

    // Also write to legacy path for backward compat
    writeFileSync(LEGACY_SESSION_FILE, sections.join('\n'))
  } catch {}
}

/**
 * Save a PostCompact summary (Claude's own LLM-generated summary) per-session.
 */
export function savePostCompactSummary(summary: string, cwd: string | null): void {
  try {
    const dir = getSessionsDir(cwd)
    mkdirSync(dir, { recursive: true })

    const content = [
      `# Last Session (saved by clauditor via PostCompact)`,
      ``,
      `> This summary was generated by Claude while it still had full context.`,
      ``,
      summary.trim(),
      ``,
    ].join('\n')

    const timestamp = Date.now()
    writeFileSync(resolve(dir, `${timestamp}.md`), content)
    writeFileSync(LEGACY_SESSION_FILE, content)
  } catch {}
}

export interface HandoffFile {
  path: string
  content: string
  timestamp: number
  isPostCompact: boolean
}

/**
 * Read recent handoff files for a given cwd (last 24 hours).
 * Returns them sorted by timestamp, most recent first.
 */
export function readRecentHandoffs(cwd: string | null): HandoffFile[] {
  const results: HandoffFile[] = []
  const cutoff = Date.now() - MAX_HANDOFF_AGE_MS

  // Check per-session directory
  const dir = getSessionsDir(cwd)
  try {
    const files = readdirSync(dir).filter(f => f.endsWith('.md'))
    for (const file of files) {
      const filePath = resolve(dir, file)
      try {
        // Use filename timestamp (more reliable than mtime for age check)
        const fileTs = parseInt(basename(file, '.md'), 10)
        const stat = statSync(filePath)
        const effectiveTs = isNaN(fileTs) ? stat.mtimeMs : fileTs

        if (effectiveTs < cutoff) {
          // Clean up old files
          try { unlinkSync(filePath) } catch {}
          continue
        }
        const content = readFileSync(filePath, 'utf-8')
        results.push({
          path: filePath,
          content,
          timestamp: effectiveTs,
          isPostCompact: content.includes('PostCompact'),
        })
      } catch {}
    }
  } catch {
    // Directory doesn't exist yet
  }

  // Fallback: check legacy file if no per-session files found
  if (results.length === 0) {
    try {
      const stat = statSync(LEGACY_SESSION_FILE)
      if (stat.mtimeMs >= cutoff) {
        const content = readFileSync(LEGACY_SESSION_FILE, 'utf-8')
        results.push({
          path: LEGACY_SESSION_FILE,
          content,
          timestamp: stat.mtimeMs,
          isPostCompact: content.includes('PostCompact'),
        })
      }
    } catch {}
  }

  return results.sort((a, b) => b.timestamp - a.timestamp)
}

/**
 * Read the most recent session state. Returns null if nothing saved.
 * For backward compatibility with code that uses the old API.
 */
export function readLastSessionState(): string | null {
  try {
    return readFileSync(LEGACY_SESSION_FILE, 'utf-8')
  } catch {
    return null
  }
}

/**
 * Extract session state data from a JSONL transcript.
 */
export function extractSessionStateFromTranscript(
  sessionId: string,
  transcriptPath: string
): SessionStateData | null {
  try {
    const content = readFileSync(transcriptPath, 'utf-8')
    const lines = content.split('\n')

    let cwd: string | null = null
    let branch: string | null = null
    let turnCount = 0
    const turnTokens: number[] = []
    const filesModified = new Set<string>()
    const filesRead = new Set<string>()
    const gitCommits: string[] = []
    const keyCommands: string[] = []
    const userMessages: string[] = []
    let originalTask: string | null = null
    let lastAssistantMessage: string | null = null

    // Get cwd and branch from most recent user record
    for (let i = lines.length - 1; i >= 0; i--) {
      try {
        const r = JSON.parse(lines[i])
        if (r.type === 'user' && r.cwd) {
          cwd = r.cwd
          branch = r.gitBranch || null
          break
        }
      } catch {}
    }

    // Scan all records
    for (const line of lines) {
      try {
        const r = JSON.parse(line)

        // Extract user messages (skip meta/system messages)
        if (r.type === 'user' && !r.isMeta) {
          const msg = extractUserMessage(r)
          if (msg && !msg.startsWith('<')) {
            userMessages.push(msg)
            if (!originalTask) originalTask = msg
          }
        }

        // Count turns
        if (r.type === 'assistant' && r.message?.usage) {
          const u = r.message.usage
          const total = (u.input_tokens || 0) + (u.output_tokens || 0) +
            (u.cache_creation_input_tokens || 0) + (u.cache_read_input_tokens || 0)
          turnTokens.push(total)
          turnCount++
        }

        // Extract tool calls + last assistant text
        if (r.type === 'assistant' && r.message?.content) {
          // Capture the last assistant text message (often contains plan/next steps)
          const textBlocks = (r.message.content as Array<{ type: string; text?: string }>)
            .filter((b: { type: string; text?: string }) => b.type === 'text' && b.text)
            .map((b: { type: string; text?: string }) => b.text!)
          if (textBlocks.length > 0) {
            lastAssistantMessage = textBlocks.join('\n').trim()
          }

          for (const block of r.message.content) {
            if (block.type !== 'tool_use') continue

            // Files modified
            if (block.name === 'Edit' || block.name === 'Write') {
              const fp = block.input?.file_path
              if (fp) filesModified.add(fp.split('/').pop() || fp)
            }

            // Files read
            if (block.name === 'Read') {
              const fp = block.input?.file_path
              if (fp) filesRead.add(fp.split('/').pop() || fp)
            }

            // Bash commands — extract git commits, test results, builds
            if (block.name === 'Bash') {
              const cmd = block.input?.command as string | undefined
              if (!cmd) continue

              // Git commits — various formats
              if (cmd.includes('git') && cmd.includes('commit')) {
                let commitMsg: string | null = null

                // HEREDOC format first (most common in Claude Code): -m "$(cat <<'EOF'\nmessage\nEOF\n)"
                if (cmd.includes('<<')) {
                  const heredocMatch = cmd.match(/<<['"]?EOF['"]?\)?\s*\n\s*(.+)/)
                  if (heredocMatch) commitMsg = heredocMatch[1].trim()
                }

                // Standard formats: -m "message" or -m 'message'
                if (!commitMsg) {
                  const match = cmd.match(/-m\s+["']([^"'\n]+)["']/) ||
                    cmd.match(/commit\s+-m\s+"([^"\n]+)"/) ||
                    cmd.match(/commit\s+-m\s+'([^'\n]+)'/)
                  if (match) commitMsg = match[1].trim()
                }

                if (commitMsg) {
                  gitCommits.push(commitMsg.slice(0, 120))
                }
              }

              // Key commands: tests, builds, deploys, installs
              if (/\b(test|build|deploy|lint|format|install|migrate|seed)\b/i.test(cmd)) {
                const shortCmd = cmd.split('\n')[0].slice(0, 100)
                keyCommands.push(shortCmd)
              }
            }
          }
        }

        // Also check tool results in user messages (where Claude Code puts them)
        if (r.type === 'user' && Array.isArray(r.message?.content)) {
          for (const block of r.message.content) {
            if (block.type === 'tool_result' && typeof block.content === 'string') {
              // Check for test results
              if (/passed|failed|error/i.test(block.content) && block.content.length < 200) {
                const resultLine = block.content.split('\n').find(
                  (l: string) => /passed|failed|succeeded|error/i.test(l)
                )
                if (resultLine) {
                  keyCommands.push(`→ ${resultLine.trim().slice(0, 100)}`)
                }
              }
            }
          }
        }
      } catch {}
    }

    if (turnTokens.length < 5) return null

    const baseline = turnTokens.slice(0, 5).reduce((a, b) => a + b, 0) / 5
    const current = turnTokens.slice(-5).reduce((a, b) => a + b, 0) / 5
    const wasteFactor = baseline > 0 ? Math.round(current / baseline) : 1

    // Deduplicate key commands (same command run multiple times)
    const uniqueCommands = [...new Set(keyCommands)].slice(0, 10)

    // Get last 3 user messages (most recent decisions)
    const recentUserMessages = userMessages
      .slice(-3)
      .map(m => m.slice(0, 200))

    // Truncate original task
    if (originalTask && originalTask.length > 300) {
      originalTask = originalTask.slice(0, 300) + '...'
    }

    return {
      savedAt: new Date().toISOString().slice(0, 16).replace('T', ' '),
      branch,
      turns: turnCount,
      tokensPerTurn: Math.round(current / 1000),
      wasteFactor,
      filesModified: Array.from(filesModified),
      filesRead: Array.from(filesRead),
      cwd,
      originalTask,
      recentUserMessages,
      gitCommits,
      keyCommands: uniqueCommands,
      lastAssistantMessage: lastAssistantMessage ? lastAssistantMessage.slice(0, 500) : null,
    }
  } catch {
    return null
  }
}

/**
 * Extract the text content from a user record.
 */
function extractUserMessage(record: Record<string, unknown>): string | null {
  const msg = record.message as { content?: unknown } | undefined
  if (!msg?.content) return null

  if (typeof msg.content === 'string') {
    return msg.content.trim() || null
  }

  if (Array.isArray(msg.content)) {
    // Find text blocks, skip tool_result blocks
    const textParts = (msg.content as Array<{ type: string; text?: string }>)
      .filter(b => b.type === 'text' && b.text)
      .map(b => b.text!)
    return textParts.join(' ').trim() || null
  }

  return null
}

/**
 * Find transcript path for a session ID.
 */
export function findTranscriptPathSync(sessionId: string): string | null {
  const projectsDir = resolve(homedir(), '.claude/projects')
  try {
    const dirs = readdirSync(projectsDir, { withFileTypes: true })
    for (const dir of dirs) {
      if (!dir.isDirectory()) continue
      const candidate = resolve(projectsDir, dir.name, `${sessionId}.jsonl`)
      try {
        readFileSync(candidate, { flag: 'r' })
        return candidate
      } catch {}
    }
  } catch {}
  return null
}
