import { writeFileSync, mkdirSync } from 'node:fs'
import { homedir } from 'node:os'
import { resolve } from 'node:path'
import { logActivity } from '../features/activity-log.js'
import { readStdin, outputDecision } from './shared.js'

const CLAUDITOR_DIR = resolve(homedir(), '.clauditor')
const LAST_SESSION_FILE = resolve(CLAUDITOR_DIR, 'last-session.md')

/**
 * PostCompact hook handler.
 *
 * Fires AFTER Claude Code compacts the conversation. Receives `compact_summary`
 * — Claude's own LLM-generated summary of the session, created while it still
 * had full context. This is dramatically better than mechanical JSONL extraction
 * because the LLM knows the reasoning, blockers, and plan.
 *
 * Saves the summary to ~/.clauditor/last-session.md for injection on next SessionStart.
 */
export async function handlePostCompactHook(): Promise<void> {
  const input = await readStdin()
  let hookInput: {
    session_id: string
    cwd?: string
    hook_event_name: string
    trigger?: string
    compact_summary?: string
  }

  try {
    hookInput = JSON.parse(input)
  } catch {
    outputDecision({})
    return
  }

  const summary = hookInput.compact_summary
  if (!summary || summary.trim().length === 0) {
    outputDecision({})
    return
  }

  try {
    mkdirSync(CLAUDITOR_DIR, { recursive: true })

    const content = [
      `# Last Session (saved by clauditor via PostCompact)`,
      ``,
      `> This summary was generated by Claude while it still had full context.`,
      `> It captures reasoning, decisions, and plans that mechanical extraction cannot.`,
      ``,
      summary.trim(),
      ``,
    ].join('\n')

    writeFileSync(LAST_SESSION_FILE, content)

    logActivity({
      type: 'context_warning',
      session: hookInput.session_id?.slice(0, 8) || 'unknown',
      message: `PostCompact: saved Claude's own summary (${summary.length} chars)`,
    }).catch(() => {})
  } catch {
    // Non-critical — don't break the hook
  }

  // PostCompact has no decision control
  outputDecision({})
}

// Run if invoked directly
handlePostCompactHook().catch((err) => {
  process.stderr.write(`clauditor post-compact hook error: ${err}\n`)
  process.stdout.write('{}')
  process.exit(0)
})
