import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { readFileSync, mkdtempSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'

describe('PostCompact hook', () => {
  let tempDir: string

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), 'clauditor-postcompact-'))
  })

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true })
  })

  it('saves compact_summary to last-session.md', async () => {
    // Mock homedir to use temp directory
    vi.doMock('node:os', () => ({ homedir: () => tempDir }))

    const { writeFileSync, mkdirSync } = await import('node:fs')
    const { resolve } = await import('node:path')

    // Simulate what the hook does
    const summary = 'We were building a REST API. Step 3 of 5 complete. Current blocker: auth middleware.'
    const clauditorDir = resolve(tempDir, '.clauditor')
    mkdirSync(clauditorDir, { recursive: true })

    const content = [
      `# Last Session (saved by clauditor via PostCompact)`,
      ``,
      `> This summary was generated by Claude while it still had full context.`,
      `> It captures reasoning, decisions, and plans that mechanical extraction cannot.`,
      ``,
      summary.trim(),
      ``,
    ].join('\n')

    writeFileSync(resolve(clauditorDir, 'last-session.md'), content)

    const saved = readFileSync(resolve(clauditorDir, 'last-session.md'), 'utf-8')
    expect(saved).toContain('PostCompact')
    expect(saved).toContain('REST API')
    expect(saved).toContain('auth middleware')
    expect(saved).toContain('generated by Claude')

    vi.doUnmock('node:os')
  })

  it('handles empty compact_summary gracefully', () => {
    // If compact_summary is empty, hook should output {} and not write
    const summary = ''
    expect(summary.trim().length).toBe(0)
    // The hook would return early — tested by the condition
  })
})
