import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { mkdtempSync, writeFileSync, readFileSync, mkdirSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'

describe('PostCompact summary preservation', () => {
  let tempDir: string

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), 'clauditor-overwrite-test-'))
  })

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true })
  })

  it('PostCompact summary is not overwritten by mechanical extraction', () => {
    const clauditorDir = join(tempDir, '.clauditor')
    mkdirSync(clauditorDir, { recursive: true })
    const lastSessionPath = join(clauditorDir, 'last-session.md')

    // Simulate PostCompact writing Claude's rich summary
    const postCompactContent = [
      '# Last Session (saved by clauditor via PostCompact)',
      '',
      '> This summary was generated by Claude while it still had full context.',
      '',
      'We were building a REST API. Step 3 complete. Blocker: auth middleware.',
    ].join('\n')
    writeFileSync(lastSessionPath, postCompactContent)

    // Verify PostCompact content is there
    expect(readFileSync(lastSessionPath, 'utf-8')).toContain('PostCompact')
    expect(readFileSync(lastSessionPath, 'utf-8')).toContain('auth middleware')

    // Simulate what PostToolUse block does — check before overwriting
    const existingContent = readFileSync(lastSessionPath, 'utf-8')
    const shouldSaveMechanical = !existingContent.includes('PostCompact')

    expect(shouldSaveMechanical).toBe(false) // should NOT overwrite

    // PostCompact content survives
    expect(readFileSync(lastSessionPath, 'utf-8')).toContain('auth middleware')
  })

  it('mechanical extraction is saved when no PostCompact summary exists', () => {
    const clauditorDir = join(tempDir, '.clauditor')
    mkdirSync(clauditorDir, { recursive: true })
    const lastSessionPath = join(clauditorDir, 'last-session.md')

    // No file exists — shouldSaveMechanical should be true
    let shouldSaveMechanical = true
    try {
      const existingContent = readFileSync(lastSessionPath, 'utf-8')
      if (existingContent.includes('PostCompact')) {
        shouldSaveMechanical = false
      }
    } catch {
      // File doesn't exist
    }

    expect(shouldSaveMechanical).toBe(true)
  })

  it('mechanical extraction overwrites old mechanical extraction', () => {
    const clauditorDir = join(tempDir, '.clauditor')
    mkdirSync(clauditorDir, { recursive: true })
    const lastSessionPath = join(clauditorDir, 'last-session.md')

    // Old mechanical extraction (no PostCompact marker)
    writeFileSync(lastSessionPath, '# Last Session (saved by clauditor)\n\n- **Branch:** old-branch')

    let shouldSaveMechanical = true
    try {
      const existingContent = readFileSync(lastSessionPath, 'utf-8')
      if (existingContent.includes('PostCompact')) {
        shouldSaveMechanical = false
      }
    } catch {}

    expect(shouldSaveMechanical).toBe(true) // should overwrite old mechanical
  })
})
